---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true

ratings:
   paths:
   - Gemfile.lock
   - "app/**"
   - "lib/**"
   - "**.rb"
   - "**.js"
   - "**.css"

exclude_paths:
- spec/**/*
- config/**/*
