---
app_name: HieraViz
basepath: "../puppet2.7"
classpath: "farm_modules/%s/manifests/init.pp"
hierafile: "dev/hiera-local.yaml"
usedb: true
puppetdb:
  usessl: false
  host: puppetdb.sd2.0x35.net
  port: 8080
http_auth:
  username: 'xxx'
  password: 'xxx'
