---
app_name: HieraViz
basepath: "../puppet"
classpath: "farm_modules/%s/manifests/init.pp"
hierafile: "dev/hiera-local.yaml"
session_seed: "xxx"
usedb: true
puppetdb:
  usessl: false
  host: puppetdb.example.com
  port: 8080
auth_method: http
http_auth:
  username: 'xxx'
  password: 'xxx'
oauth2_auth:
  host: gitlab.example.com
  application_id: xxxxxxxx
  secret: xxxxxxxx
  resource_required: '/api/v3/projects/namespace%2Fsome_repo'
  required_response_key: 'id'
  required_response_value: '42'
