---
basepath: "spec/files/puppet"
classpath: "farm_modules/%s/manifests/init.pp"
hierafile: "spec/files/hiera.yml"
usedb: true
puppetdb:
  usessl: false
  host: puppetdb.example.com
  port: 8080
http_auth:
  username: 'toto'
  password: 'toto'
