---
basepath: "spec/files/puppet"
classpath: "farm_modules/%s/manifests/init.pp"
hierafile: "hiera.yml"
session_seed: "toto"
usedb: false
puppetdb:
  usessl: false
  host: puppetdb.example.com
  port: 8080
auth_method: http
http_auth:
  username: 'toto'
  password: 'toto'
