---
app_name: HieraViz
basepath: "../puppet"
basepath_dir: "../puppet*" # use patterns that Dir.glob can read
classpath: "farm_modules/%s/manifests/init.pp"
hierafile: "dev/hiera-local.yaml"
tmpdir: "/tmp"
session_seed: "xxx"
session_renew: 3600
defaultscope:
  operatingsystem: Debian
  lsbdistcodename: jessie
debug: false
puppetdb:
  usessl: false
  host: puppetdb.example.com
  port: 8080
auth_method: http
http_auth:
  username: 'xxx'
  password: 'xxx'
  access_token: '123456'
gitlab_auth:
  host: https://gitlab.example.com
  application_id: xxxxxxxx
  secret: xxxxxxxx
  resource_required: '/api/v3/projects/namespace%2Fsome_repo'
  required_response_key: 'id'
  required_response_value: '42'
